name: Deploy to Server

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment (dev or prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      build_confirmation:
        description: 'Type "yes" to confirm the build'
        required: true
        default: 'no'

jobs:
  deploy:
    if: ${{ github.event.inputs.build_confirmation == 'yes' }}
    runs-on: ubuntu-latest

    env:
      SSH_USER: ${{ secrets.SSH_USER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Deployment Variables
        id: set-vars
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "TARGET_FILE=dev/de.html" >> $GITHUB_ENV
            echo "TMP_FILE=/tmp/dev_de.html" >> $GITHUB_ENV
            echo "SERVER_IP=${{ secrets.DEV_SERVER_IP }}" >> $GITHUB_ENV
            echo "${{ secrets.DEV_SSH_KEY }}" > private_key.pem
          else
            echo "TARGET_FILE=prod/prod.html" >> $GITHUB_ENV
            echo "TMP_FILE=/tmp/prod_prod.html" >> $GITHUB_ENV
            echo "SERVER_IP=${{ secrets.PROD_SERVER_IP }}" >> $GITHUB_ENV
            echo "${{ secrets.PROD_SSH_KEY }}" > private_key.pem
          fi
          chmod 600 private_key.pem

      - name: Copy File to Remote Server
        run: |
          cp "$TARGET_FILE" "$TMP_FILE"
          scp -o StrictHostKeyChecking=no -i private_key.pem "$TMP_FILE" "$SSH_USER@$SERVER_IP:/home/$SSH_USER/"
          ssh -o StrictHostKeyChecking=no -i private_key.pem "$SSH_USER@$SERVER_IP" "ls -l /home/$SSH_USER/"
